### ISSUE TITLE
Error when quickloading on CCL on Windows

### ISSUE THREAD

**Issue by phoe** [didierverna/clon#3]
Clozure Common Lisp Version 1.11-r16635  (WindowsX8664)

```
? (ql:quickload :net.didierverna.clon)
To load "net.didierverna.clon":
  Load 1 ASDF system:
    cffi
  Install 1 Quicklisp release:
    cl-clon
; Fetching #<URL "http://beta.quicklisp.org/archive/cl-clon/2015-07-09/clon-1.0b24.tgz">
; 186.53KB
==================================================
191,003 bytes in 0.12 seconds (1492.21KB/sec)
; Loading "net.didierverna.clon"
[package net.didierverna.clon.setup]..............
[package net.didierverna.clon]....................
.........................
Read error between positions 4979 and 7234 in C:/Users/phoe/quicklisp/dists/quicklisp/software/clon-1.0b24/termio/termio.lisp.
> Error: Foreign variable "TIOCGWINSZ" not found
> While executing: CCL::%LOAD-VAR, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
```

**Comment by didierverna** [comment]
TIOCGWINSZ is a Posix variable. I'm guessing you're on native windows without a posix environment. I don't know Windows at all so I can't provide support for it, but there are ways around this kind of portability problems already. I suggest you read appendix A of the [user manual](https://www.lrde.epita.fr/~didier/software/lisp/clon/user/Technical-Notes.html#Technical-Notes) (notably the first 3 sections). Section 2 Installation may also help.

**Comment by phoe** [comment]
Okay. I'll close it for now - I'm doing other things at the moment and cannot really test it on Windows.
