### ISSUE TITLE
Print usage on error

### ISSUE THREAD

**Issue by Ferada** [didierverna/clon#4]
The `clon-error-handler` has only a limited set of options, none of which print the help output when an error occurs. I also found it hard to implement that, `handler-case` doesn't work because errors are caught before I get a chance to handle them, patching the error handler or `exit-abnormally` are also not possible since the context isn't fully constructed yet when it's still parsing the command line options.

So, is there any way to run `help` when the supplied command line options were invalid for any reason?

**Comment by didierverna** [comment]
Hi, thanks for your feedback.

Could you be a bit more specific (with an example perhaps)? In particular, what kind of error are you talking about: when an option is not used correctly or something else? In case of misuse, there's already a number of useful restarts, but perhaps it would be good to be able to print this particular option's help string.

But I'm not sure this is what you're talking about.

**Comment by Ferada** [comment]
Yes, when an option was used incorrectly, options were missing and similar cases. Some command line tools immediately print an error and then the same output as with `--help` when an option was wrongly specified, so I wanted to replicate that. I'll see if I can add an example here later.

**Comment by didierverna** [comment]
I'm re-opening this because I don't know why it was closed. Perhaps there is something I can do in the library to help with this (it looks like a feature request). I'll have to immerse myself back in the code first...

**Comment by didierverna** [comment]
Hi,

I looked into this, and it was in fact much simpler to implement than I had anticipated. There's a new value to the --clon-error-handler option / CLON_ERROR_HANDLER env var, namely "help" that does what you want. The end user manual is now up to date, and the change has been pushed to the trunk. Too bad I tagged a new release just yesterday.

I'm closing this for good now.
