### ISSUE TITLE
Mention license also in sub-systems?

### ISSUE THREAD

**Issue by phmarek** [didierverna/clon#7]
Hi Didi,

the `CLON` asdf says that the license is `BSD`.
Would you mind repeating that in `net.didierverna.clon.setup` and `net.didierverna.clon.setup/termio`?

I've got short function that reports the licenses of all the systems in use, and these two come up as `NIL`.

Thanks a lot!

**Comment by didierverna** [comment]
Hi!

AFAICS, those systems already have the requested information, as per commit d74dfe7f (June 24 2015). Aren't you using an old version ?

**Comment by phmarek** [comment]
My QL got me a 1.0b24, which is also the latest tag here - but doesn't include `:license` in the `setup/net.didierverna.clon.setup.asd` definition.

So, what's your definition of "old"? ;)

I just did a `(QL:UPDATE-ALL-DISTS)` but got no `clon` update....

**Comment by didierverna** [comment]
I see. QL must still have the b24 version, and the commit that I'm talking about came right after it, in 2015 :-) It's on the trunk, but there is no further tag or release since then. I suppose I have to make a new release for it to go to QL.

**Comment by phmarek** [comment]
Yes, please!

**Comment by didierverna** [comment]
1.0b25 is out now. It should propagate to the next Quicklisp release, so I'm closing this.
